import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service - ResumePilot',
  description: 'Read the terms and conditions for using the ResumePilot platform.',
};

export default function TermsOfServicePage() {
  return (
    <div className="legal-page">
      <Link href="/" className="btn btn-ghost btn-sm" style={{ marginBottom: 'var(--space-6)', display: 'inline-flex' }}>
        <ArrowLeft size={16} />
        Back to Home
      </Link>

      <h1>Terms of Service</h1>
      <p style={{ color: 'var(--color-text-tertiary)', marginBottom: 'var(--space-8)' }}>
        Last updated: May 2026
      </p>

      <p>
        Welcome to ResumePilot. By accessing or using our platform, you agree to be bound by these
        Terms of Service. Please read them carefully before using our services.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        By creating an account or using ResumePilot in any way, you agree to these Terms of Service
        and our Privacy Policy. If you do not agree to these terms, you may not use the platform.
        We reserve the right to update these terms at any time, and your continued use of the
        platform constitutes acceptance of any modifications.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        ResumePilot is an AI-powered resume optimization platform that helps users tailor their
        resumes to specific job descriptions. Our services include ATS compatibility scoring,
        keyword analysis, resume content optimization, and AI-generated interview preparation
        questions. We continuously improve our AI models and features to provide the best possible
        experience.
      </p>

      <h2>3. User Accounts</h2>
      <p>
        You are responsible for maintaining the confidentiality of your account credentials,
        including your password. You agree to provide accurate and complete information during
        registration and to keep your account information up to date. You are responsible for all
        activity that occurs under your account. Notify us immediately if you suspect unauthorized
        access to your account.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the platform for any unlawful purpose or in violation of any applicable laws.</li>
        <li>Attempt to gain unauthorized access to our systems, other user accounts, or any data you are not authorized to access.</li>
        <li>Use automated scripts, bots, or scrapers to access the platform without prior written consent.</li>
        <li>Upload or submit harmful, malicious, or deceptive content.</li>
        <li>Resell, redistribute, or sublicense access to the platform without authorization.</li>
        <li>Interfere with or disrupt the integrity or performance of the platform.</li>
      </ul>

      <h2>5. Content Ownership</h2>
      <p>
        You retain full ownership of all resume content, personal information, and job descriptions
        you submit to ResumePilot. By using our services, you grant us a limited, non-exclusive
        license to process your content solely for the purpose of providing and improving our
        optimization services. We do not claim ownership of your data, and we will not share your
        individual content with third parties except as required to provide the service.
      </p>

      <h2>6. AI-Generated Content</h2>
      <p>
        The optimized resume content, ATS scores, keyword suggestions, and interview questions
        generated by our AI are provided as suggestions to assist you. You are responsible for
        reviewing and verifying the accuracy of all AI-generated content before using it.
        ResumePilot does not guarantee that using our optimized content will result in employment
        or interviews. AI-generated content should be treated as a starting point that you
        customize to accurately represent your experience and qualifications.
      </p>

      <h2>7. Free and Paid Plans</h2>
      <p>
        ResumePilot offers both free and paid subscription plans. Free plans include a limited
        number of resume optimizations per month. Paid plans provide higher usage limits and
        additional features. Pricing is subject to change with at least 30 days&apos; notice to
        existing subscribers. Downgrading from a paid plan may result in the loss of access to
        premium features at the end of the current billing cycle.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        ResumePilot is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. To
        the maximum extent permitted by law, ResumePilot and its affiliates shall not be liable for
        any indirect, incidental, special, consequential, or punitive damages, including but not
        limited to loss of profits, data, employment opportunities, or goodwill, arising from your
        use of the platform. Our total liability for any claim related to the service shall not
        exceed the amount you paid us in the 12 months preceding the claim.
      </p>

      <h2>9. Termination</h2>
      <p>
        We may suspend or terminate your account if you violate these Terms of Service, engage in
        fraudulent or abusive behavior, or for any other reason at our discretion with reasonable
        notice. You may close your account at any time through the Settings page. Upon termination,
        your data will be handled in accordance with our Privacy Policy, including deletion within
        30 days of account closure.
      </p>

      <h2>10. Contact</h2>
      <p>
        If you have any questions about these Terms of Service, please contact us at{' '}
        <a href="mailto:guys4929@gmail.com">guys4929@gmail.com</a>.
      </p>

      <div style={{ marginTop: 'var(--space-12)', paddingTop: 'var(--space-6)', borderTop: '1px solid var(--color-border)' }}>
        <Link href="/" className="btn btn-ghost btn-sm">
          <ArrowLeft size={16} />
          Back to Home
        </Link>
      </div>
    </div>
  );
}
